---
- name: "AFTER_SYMLINK (ANSISTRANO) | test rbenv/ruby installation and version"
  shell: "rbenv version-name"
  ignore_errors: true
  register: rbenv_version_name
  become: true
  become_user: "{{ deploy_user }}"

# TODO: if this assert is passing, we should be able to remove 
#       `environment:` from the following tasks
- name: "AFTER_SYMLINK (ANSISTRANO) | assert ruby-version = 2.7.1"
  assert:
    that:
      - rbenv_version_name.stdout == "2.7.1"

- name: AFTER_SYMLINK (ANSISTRANO) | install bundled gems
  bundler:
    chdir: "{{ ansistrano_release_path.stdout }}"
    executable: "{{ bundle_path }}"
    deployment_mode: yes
    exclude_groups:
      - development
      - test
  become: true
  become_user: "{{ deploy_user }}"

- name: AFTER_SYMLINK (ANSISTRANO) | precompile assets
  command: "{{ bundle_path }} exec rake assets:precompile"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  become: true
  become_user: "{{ deploy_user }}"

- name: AFTER_SYMLINK (ANSISTRANO) | migrate the db
  command: "{{ bundle_path }} exec rake neo4j:migrate"
  run_once: true
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  notify: restart nginx
