---
- name: install openjdk-11
  apt:
    name: openjdk-11-jdk-headless

- name: install neo4j server
  import_role:
    name: kevincoakley.neo4j

- name: set the neo4j TLS level
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^dbms.connector.bolt.tls_level=.*'
    line: "dbms.connector.bolt.tls_level={{ neo4j_connector_bolt_tls_level }}"
    state: present
  notify: Restart Neo4j

- name: set the neo4j database name
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^dbms.active_database=.*'
    line: "dbms.active_database={{ neo4j_active_database }}"
    state: present
  notify: Restart Neo4j

# TODO: seriously consider ditching `kevincoakly.neo4j` and writing a custom role
- debug:
    msg: "neo4j_password is defined? '{{ neo4j_password is defined and neo4j_password|string }}'"
  tags: neo4j-force-password

- name: reset the neo4j password since that stupid 'initial password' thing always fails
  uri:
    url: http://localhost:7474/user/neo4j/password
    user: neo4j
    password: neo4j
    method: POST
    body: "{'password':'{{ neo4j_password }}'}"
    force_basic_auth: yes
    status_code: 200 # not 201
    body_format: json
  tags: neo4j-force-password
