---
- name: "test rbenv/ruby installation and version"
  shell: "rbenv version-name"
  ignore_errors: true
  register: rbenv_version_name
  become: true
  become_user: "{{ deploy_user }}"

- assert:
    that:
      - rbenv_version_name.stdout == "2.7.1"

- name: AFTER_SYMLINK (ANSISTRANO) | install bundled gems
  environment:
    RBENV_ROOT: '{{ rbenv_root }}'
    PATH: '{{ rbenv_root }}/bin:{{ rbenv_root }}/shims:{{ rbenv_root }}/plugins/ruby-build/bin:{{ ansible_env.PATH }}'
  bundler:
    chdir: "{{ ansistrano_release_path.stdout }}"
    executable: "{{ bundle_path }}"
    deployment_mode: yes
    exclude_groups:
      - development
      - test
  become: true
  become_user: "{{ deploy_user }}"

- name: AFTER_SYMLINK (ANSISTRANO) | precompile assets
  environment:
    RAILS_ENV: 'production'
    NODE_ENV: 'production'
    RBENV_ROOT: '{{ rbenv_root }}'
    PATH: '{{ rbenv_root }}/bin:{{ rbenv_root }}/shims:{{ rbenv_root }}/plugins/ruby-build/bin:{{ ansible_env.PATH }}'
  command: "{{ bundle_path }} exec rake assets:precompile"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  become: true
  become_user: "{{ deploy_user }}"

# TODO: migrate the indexes/constraints (once neo4j db is created)
# - name: migrate the db
#   command: "{{ bundle_path }} exec rake db:migrate"
#   run_once: true
#   args:
#     chdir: "{{ ansistrano_release_path.stdout }}"
