---
- name: install openjdk-11
  apt:
    name: openjdk-11-jdk-headless

- name: install neo4j server
  import_role:
    name: kevincoakley.neo4j

# https://github.com/kevincoakley/ansible-role-neo4j/blob/master/tasks/main.yml
# https://stackoverflow.com/questions/45784232/how-to-create-new-database-in-neo4j

- name: set the neo4j TLS level
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^dbms.connector.bolt.tls_level=.*'
    line: "dbms.connector.bolt.tls_level={{ neo4j_connector_bolt_tls_level }}"
    state: present
  notify: Restart Neo4j

- name: set the neo4j database name
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^dbms.active_database=.*'
    line: "dbms.active_database={{ neo4j_active_database }}"
    state: present
  notify: Restart Neo4j
