---
- hosts: all
  remote_user: "{{ deploy_user }}"
  gather_facts: false
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/.."
    ansistrano_deploy_to: "/opt/pariyatti/kosa"
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: https://github.com/pariyatti/kosa.git
    rails_env: "development" # TODO: use a real environment
  roles:
    - ansistrano.deploy

  tasks:
    # TODO: is this necessary at all? -sd
    - name: Set RAILS_ENV
      lineinfile:
        path: /etc/environment
        regexp: '^RAILS_ENV='
        line: "RAILS_ENV={{rails_env}}"

