---
- hosts: all
  remote_user: "{{ deploy_user }}"
  gather_facts: true
  environment:
    RAILS_ENV: production
    RBENV_ROOT: '{{ rbenv_root }}'
    PATH: '{{ rbenv_root }}/bin:{{ rbenv_root }}/shims:{{ rbenv_root }}/plugins/ruby-build/bin:{{ ansible_env.PATH }}'
  roles:
    - { role: deploy, tags: ['deploy'] }
    - { role: ansistrano.deploy, tags: ['ansistrano.deploy'] }
