---
- name: update apt cache
  apt: update_cache=yes
  become: true

- name: install aptitude
  apt: name=aptitude state=present
  become: true

- name: upgrade the distro
  apt: upgrade=safe
  become: true

- name: install common packages
  apt: 
    pkg:
      - apache2-utils
      - bison
      - build-essential
      - cron
      - curl
      - fail2ban
      - git-core
      - htop
      - less
      - libcurl4-openssl-dev
      - libffi-dev
      - libmagickwand-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - libyaml-dev
      - logrotate
      # NOTE: nodejs is installed via kosa/deployment/roles/nodejs
      - openssl
      - python3-pexpect
      - python3-software-properties
      - redis-tools
      - rsync
      - sqlite3
      - ufw
      - unattended-upgrades
      - vim
      - wget
      - xvfb
      - zlib1g-dev
    state: latest
  become: true

- name: update hostname
  hostname:
    name: "{{ domain_name }}"
  become: true

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ domain_name }}'
    state: present
  become: true

- name: Reboot system if required
  shell: sleep 2 && shutdown -r now 'Rebooting to complete system upgrade'
  async: 1
  poll: 0
  args:
    removes: /var/run/reboot-required
  become: true
  register: restart_system

- name: Wait for server to restart
  # local_action: wait_for host={{ domain_name }} port={{ ansible_port }} delay=2 timeout=3000
  local_action: wait_for host={{ domain_ip }} port={{ ansible_port }} delay=2 timeout=3000
  when: restart_system.changed

- name: ensure fail2ban is running
  become: true
  action: service name=fail2ban state=restarted enabled=yes

- name: configure sshd
  copy: src=etc/ssh/sshd_config dest=/etc/ssh/sshd_config
  become: true
  notify: restart ssh

- name: Ensure group "deploy" exists
  group:
    name: deploy
    state: present
  become: true

- name: create deploy user
  user:
    name: deploy
    group: deploy
    append: true
    state: present
    create_home: true
    shell: /bin/bash
  become: true

- name: Allow 'deploy' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%deploy'
    line: '%deploy ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: enable systemctl services for deploy user
  become: true
  shell: loginctl enable-linger deploy

# TODO: enable UFW later, if need be. ask kitty why simple doesn't? -sd
# - name: UFW - Allow SSH connections
#   ufw:
#     rule: allow
#     name: OpenSSH
# 
# - name: UFW - Allow HTTP on 80
#   ufw:
#     rule: allow
#     port: 80
#     proto: tcp
# 
# - name: UFW - Deny all other incoming traffic by default
#   ufw:
#     state: enabled
#     policy: deny
#     direction: incoming
