- hosts: all
  gather_facts: true
  roles:
    - { role: common, tags: ['common']}
    - { role: ssh, tags: ['ssh']}
    - { role: neo4j, tags: ['neo4j']}
    - { role: rbenv, tags: ['rbenv'] }
    - { role: nodejs, tags: ['nodejs'] }
    - { role: monit, tags: ['monit'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: passenger, tags: ['passenger'] }
